-- begin HRTRAININGPLATFORM_LOCATION
alter table HRTRAININGPLATFORM_LOCATION add constraint FK_HRTRAININGPLATFORM_LOCATION_ADDRESS foreign key (ADDRESS_ID) references HRTRAININGPLATFORM_ADDRESS(ID)^
create unique index IDX_HRTRAININGPLATFORM_LOCATION_UNIQ_LOCATION_NAME on HRTRAININGPLATFORM_LOCATION (LOCATION_NAME) ^
create index IDX_HRTRAININGPLATFORM_LOCATION_ADDRESS on HRTRAININGPLATFORM_LOCATION (ADDRESS_ID)^
-- end HRTRAININGPLATFORM_LOCATION
-- begin HRTRAININGPLATFORM_ADMIN
alter table HRTRAININGPLATFORM_ADMIN add constraint FK_HRTRAININGPLATFORM_ADMIN_USER foreign key (USER_ID) references SEC_USER(ID)^
create index IDX_HRTRAININGPLATFORM_ADMIN_USER on HRTRAININGPLATFORM_ADMIN (USER_ID)^
-- end HRTRAININGPLATFORM_ADMIN
-- begin HRTRAININGPLATFORM_MANAGER
alter table HRTRAININGPLATFORM_MANAGER add constraint FK_HRTRAININGPLATFORM_MANAGER_USER foreign key (USER_ID) references SEC_USER(ID)^
create index IDX_HRTRAININGPLATFORM_MANAGER_USER on HRTRAININGPLATFORM_MANAGER (USER_ID)^
-- end HRTRAININGPLATFORM_MANAGER
-- begin HRTRAININGPLATFORM_HR_EMPLOYEE
alter table HRTRAININGPLATFORM_HR_EMPLOYEE add constraint FK_HRTRAININGPLATFORM_HR_EMPLOYEE_USER foreign key (USER_ID) references SEC_USER(ID)^
create index IDX_HRTRAININGPLATFORM_HR_EMPLOYEE_USER on HRTRAININGPLATFORM_HR_EMPLOYEE (USER_ID)^
-- end HRTRAININGPLATFORM_HR_EMPLOYEE
-- begin HRTRAININGPLATFORM_EMPLOYEE
alter table HRTRAININGPLATFORM_EMPLOYEE add constraint FK_HRTRAININGPLATFORM_EMPLOYEE_USER foreign key (USER_ID) references SEC_USER(ID)^
create index IDX_HRTRAININGPLATFORM_EMPLOYEE_USER on HRTRAININGPLATFORM_EMPLOYEE (USER_ID)^
-- end HRTRAININGPLATFORM_EMPLOYEE
-- begin HRTRAININGPLATFORM_TRAINING
alter table HRTRAININGPLATFORM_TRAINING add constraint FK_HRTRAININGPLATFORM_TRAINING_SURVEY foreign key (SURVEY_ID) references HRTRAININGPLATFORM_SURVEY(ID)^
-- end HRTRAININGPLATFORM_TRAINING
-- begin HRTRAININGPLATFORM_TRAINING_LOCATION_LINK
alter table HRTRAININGPLATFORM_TRAINING_LOCATION_LINK add constraint FK_TRALOC_TRAINING foreign key (TRAINING_ID) references HRTRAININGPLATFORM_TRAINING(ID)^
alter table HRTRAININGPLATFORM_TRAINING_LOCATION_LINK add constraint FK_TRALOC_LOCATION foreign key (LOCATION_ID) references HRTRAININGPLATFORM_LOCATION(ID)^
-- end HRTRAININGPLATFORM_TRAINING_LOCATION_LINK
-- begin HRTRAININGPLATFORM_TRAINING_EMPLOYEE_LINK
alter table HRTRAININGPLATFORM_TRAINING_EMPLOYEE_LINK add constraint FK_TRAEMP_TRAINING foreign key (TRAINING_ID) references HRTRAININGPLATFORM_TRAINING(ID)^
alter table HRTRAININGPLATFORM_TRAINING_EMPLOYEE_LINK add constraint FK_TRAEMP_EMPLOYEE foreign key (EMPLOYEE_ID) references HRTRAININGPLATFORM_EMPLOYEE(ID)^
-- end HRTRAININGPLATFORM_TRAINING_EMPLOYEE_LINK
-- begin HRTRAININGPLATFORM_CERTIFICATE
alter table HRTRAININGPLATFORM_CERTIFICATE add constraint FK_HRTRAININGPLATFORM_CERTIFICATE_FILE foreign key (FILE_ID) references SYS_FILE(ID)^
-- end HRTRAININGPLATFORM_CERTIFICATE
